# Generated by Django 3.2.7 on 2022-07-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='note',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
