# Generated by Django 3.2.7 on 2022-07-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220720_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
